default_config:

# Load the Picture Frame component
picture_frame:
  media_paths:
    - /media/album1
    - /media/album2
  allowed_extensions:
    - .jpg
    - .jpeg
    - .png
  
# Define logger levels for debugging
logger:
  default: info
  logs:
    custom_components.picture_frame: debug