title: Picture Frame Controller
views:
  - title: Picture Frame
    path: picture_frame
    icon: mdi:image-frame
    badges: []
    cards:
      - type: vertical-stack
        cards:
          # Picture display card - using the proper URL format
          - type: picture
            image: "/local{{ states('sensor.picture_frame_next_image').replace('/config', '') }}"
            title: "Current Picture Frame Image"
          
          # Source attribution card
          - type: markdown
            content: >
              **Album:** {{ state_attr('sensor.picture_frame_next_image', 'album') }}
            
      # Controls section
      - type: entities
        title: Picture Frame Controls
        show_header_toggle: false
        entities:
          - entity: input_select.album_selector
          - entity: sensor.picture_frame_current_album
          - entity: button.next_image
          - entity: button.clear_image_history
          - type: divider
          - entity: sensor.picture_frame_image_album
          - entity: sensor.picture_frame_available_albums
      
      # Technical details card
      - type: markdown
        title: Image Details
        content: >
          **Relative Path:** {{ state_attr('sensor.picture_frame_next_image', 'relative_path') }}
          
          **Path:** {{ states('sensor.picture_frame_next_image') }}
          
          **Source Path:** {{ state_attr('sensor.picture_frame_next_image', 'source_path') }}
          
          **Current Album Filter:** {{ state_attr('sensor.picture_frame_next_image', 'current_album') or 'All Albums' }}
          
          **Album:** {{ state_attr('sensor.picture_frame_next_image', 'album') }}